# Generated by Django 5.1.4 on 2025-07-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demoapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                ("primary", models.CharField(max_length=100)),
                ("secondary", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
